- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Verify node installed
  command: node -v
  register: node_version
