[local]
localhost ansible_connection=local

[webserver]
# Apna EC2 IP yahan likhna
# Example:
# 54.123.45.67 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxeldevops.pem
15.252.183.49 ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxeldevops.pem
